name: Publish Kotlin Library

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: 8
          cache: gradle
      - name: Authenticate to GitHub Packages
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew          
      - name: Publish Kotlin Library
        run: ./gradlew publish
