name: Publish Kotlin Library

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Authenticate to GitHub Packages
        uses: github/actions/setup-token@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Kotlin Library
        run: ./gradlew publish
